import fs from 'node:fs';

const [
  ,,
  inputPath = 'scraped-data/zenlish-test-2-2026/test-2-2026.raw-parts.json',
  outputPath = 'backend/src/main/resources/db/migration/V9__seed_zenlish_test_2_2026.sql',
  testSlug = 'test-2-2026',
  testTitle = 'TEST 2 - 2026',
  orderIndexArg = '100',
] = process.argv;

const parts = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const orderIndex = Number.parseInt(orderIndexArg, 10) || 100;
const varPrefix = testSlug.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');

const partTypeByName = {
  'Part 1': 'LISTENING_PART1',
  'Part 2': 'LISTENING_PART2',
  'Part 3': 'LISTENING_PART3',
  'Part 4': 'LISTENING_PART4',
  'Part 5': 'READING_PART5',
  'Part 6': 'READING_PART6',
  'Part 7': 'READING_PART7',
};

function decodeHtml(value) {
  if (!value) return '';
  return String(value)
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&#8217;/g, "'")
    .replace(/&#8211;/g, '-')
    .replace(/&#8212;/g, '-')
    .replace(/&#038;/g, '&')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ');
}

function stripHtml(value) {
  return decodeHtml(value)
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function sql(value) {
  if (value === null || value === undefined || value === false) return 'NULL';
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

function extractFirstImageUrl(html) {
  const decoded = decodeHtml(html);
  const match = decoded.match(/<img[^>]+src=["']([^"']+)["']/i);
  return match ? match[1] : null;
}

function listValues(value) {
  if (!value) return [];
  return Array.isArray(value) ? value : Object.values(value);
}

function correctAnswer(subQuestion) {
  return (subQuestion.answer || []).find((item) => item.choice_right_answer)?.choice || '';
}

function optionValue(subQuestion, letter) {
  const item = (subQuestion.answer || []).find((choice) => choice.choice === letter);
  return item?.choice_answer || '';
}

function questionContent(partName, subQuestion) {
  if (partName === 'Part 1' || partName === 'Part 2') return '';
  return stripHtml(subQuestion.title);
}

const lines = [
  `-- Seed ${testTitle} from scraped Zenlish TOEIC data.`,
  '-- Generated by scripts/build_zenlish_test_migration.mjs.',
  '',
  "INSERT INTO sections (title, slug, description, order_index, is_active)",
  `SELECT ${sql(testTitle)},`,
  `       ${sql(testSlug)},`,
  "       'Full TOEIC online test imported from Zenlish scrape: 7 parts, 200 questions.',",
  `       ${orderIndex},`,
  '       TRUE',
  `WHERE NOT EXISTS (SELECT 1 FROM sections WHERE slug = ${sql(testSlug)});`,
  '',
  `SET @${varPrefix}_section_id = (SELECT id FROM sections WHERE slug = ${sql(testSlug)} LIMIT 1);`,
  '',
];

for (const [partIndex, part] of parts.entries()) {
  const partNumber = partIndex + 1;
  const partName = `Part ${partNumber}`;
  const sectionVar = `@${varPrefix}_section_id`;
  const topicVar = `@${varPrefix}_part_${partNumber}_topic_id`;
  const exerciseVar = `@${varPrefix}_part_${partNumber}_exercise_id`;
  const slug = `${testSlug}-part-${partNumber}`;
  const exerciseType = partTypeByName[partName];
  const questionTotal = listValues(part.questions).reduce((sum, group) => sum + listValues(group.sub_questions).length, 0);
  const description = partName;

  lines.push(
    `INSERT INTO topics (section_id, title, slug, description, order_index, is_active)`,
    `SELECT ${sectionVar},`,
    `       ${sql(`${testTitle} - ${partName}`)},`,
    `       ${sql(slug)},`,
    `       ${sql(description || part.term_name)},`,
    `       ${partNumber},`,
    `       TRUE`,
    `WHERE ${sectionVar} IS NOT NULL`,
    `  AND NOT EXISTS (SELECT 1 FROM topics WHERE slug = ${sql(slug)});`,
    '',
    `SET ${topicVar} = (SELECT id FROM topics WHERE slug = ${sql(slug)} LIMIT 1);`,
    '',
    `INSERT INTO exercises (topic_id, exercise_type, total_questions, order_index, is_active)`,
    `SELECT ${topicVar}, ${sql(exerciseType)}, ${questionTotal}, ${partNumber}, TRUE`,
    `WHERE ${topicVar} IS NOT NULL`,
    `  AND NOT EXISTS (SELECT 1 FROM exercises WHERE topic_id = ${topicVar} AND exercise_type = ${sql(exerciseType)});`,
    '',
    `SET ${exerciseVar} = (`,
    `    SELECT id FROM exercises WHERE topic_id = ${topicVar} AND exercise_type = ${sql(exerciseType)} LIMIT 1`,
    `);`,
    ''
  );

  if (partName === 'Part 5') {
    for (const group of listValues(part.questions)) {
      const subQuestion = listValues(group.sub_questions)[0];
      if (!subQuestion) continue;
      const questionNumber = Number.parseInt(stripHtml(subQuestion.title), 10);
      lines.push(
        'INSERT INTO exercise_questions',
        '(exercise_id, question_number, content, option_a, option_b, option_c, option_d, correct_answer, explanation)',
        `SELECT ${exerciseVar}, ${questionNumber},`,
        `       ${sql(questionContent(partName, subQuestion))},`,
        `       ${sql(optionValue(subQuestion, 'A'))}, ${sql(optionValue(subQuestion, 'B'))}, ${sql(optionValue(subQuestion, 'C'))}, ${sql(optionValue(subQuestion, 'D'))},`,
        `       ${sql(correctAnswer(subQuestion))},`,
        `       ${sql(decodeHtml(subQuestion.explanation || ''))}`,
        `WHERE ${exerciseVar} IS NOT NULL`,
        `  AND NOT EXISTS (SELECT 1 FROM exercise_questions WHERE exercise_id = ${exerciseVar} AND question_number = ${questionNumber});`,
        ''
      );
    }
    continue;
  }

  for (const [groupIndex, group] of listValues(part.questions).entries()) {
    const groupVar = `@${varPrefix}_part_${partNumber}_group_${groupIndex + 1}_id`;
    const imageUrl = partName === 'Part 1' || partName === 'Part 3' || partName === 'Part 4'
      ? extractFirstImageUrl(group.content)
      : null;
    const passage = partName === 'Part 1' || partName === 'Part 2'
      ? ''
      : decodeHtml(group.content || '');

    lines.push(
      'INSERT INTO exercise_question_groups (exercise_id, order_index, audio_url, image_url, passage)',
      `SELECT ${exerciseVar},`,
      `       ${groupIndex + 1},`,
      `       ${sql(group.audio_url || '')},`,
      `       ${sql(imageUrl)},`,
      `       ${sql(passage)}`,
      `WHERE ${exerciseVar} IS NOT NULL`,
      `  AND NOT EXISTS (SELECT 1 FROM exercise_question_groups WHERE exercise_id = ${exerciseVar} AND order_index = ${groupIndex + 1});`,
      '',
      `SET ${groupVar} = (`,
      `    SELECT id FROM exercise_question_groups WHERE exercise_id = ${exerciseVar} AND order_index = ${groupIndex + 1} LIMIT 1`,
      `);`,
      ''
    );

    for (const subQuestion of listValues(group.sub_questions)) {
      const questionNumber = Number.parseInt(stripHtml(subQuestion.title), 10);
      lines.push(
        'INSERT INTO exercise_questions',
        '(exercise_id, group_id, question_number, content, option_a, option_b, option_c, option_d, correct_answer, explanation)',
        `SELECT ${exerciseVar}, ${groupVar}, ${questionNumber},`,
        `       ${sql(questionContent(partName, subQuestion))},`,
        `       ${sql(optionValue(subQuestion, 'A'))}, ${sql(optionValue(subQuestion, 'B'))}, ${sql(optionValue(subQuestion, 'C'))}, ${sql(optionValue(subQuestion, 'D'))},`,
        `       ${sql(correctAnswer(subQuestion))},`,
        `       ${sql(decodeHtml(subQuestion.explanation || ''))}`,
        `WHERE ${groupVar} IS NOT NULL`,
        `  AND NOT EXISTS (SELECT 1 FROM exercise_questions WHERE exercise_id = ${exerciseVar} AND question_number = ${questionNumber});`,
        ''
      );
    }
  }
}

fs.writeFileSync(outputPath, `${lines.join('\n')}\n`, 'utf8');
console.log(outputPath);
